Repository HUFS-19/How-About-This-Refactored-, pull requests merged in 2024-01, with the labels that each got.

#4 config: 깃헙 이슈, PR 템플릿 생성
  .github/ISSUE_TEMPLATE/✅-feature-template.md
  .github/ISSUE_TEMPLATE/🪲-bug-report.md
  pull_request_template.md
Labels: config

#18 Feat: Logo 이미지로 변경 / LeftLav 카테고리 선택 가능
  client/src/assets/logo.png
  client/src/components/atom/Logo.tsx
  client/src/components/atom/ProfileImg.tsx
  client/src/components/molecule/CategoryList.tsx
  client/src/components/organism/LeftNavBar.tsx
  client/src/index.tsx
  client/src/store/slice/categorySlice.tsx
  client/src/store/store.tsx
Labels: feature, migration, refactor

#20 feat: MainBox 컴포넌트 개발, Home Template 구현
  client/src/App.tsx
  client/src/components/atom/Box.tsx
  client/src/components/atom/CardBottom.tsx
  client/src/components/atom/CardImg.tsx
  client/src/components/atom/HeartIcon.tsx
  client/src/components/atom/MediumText.tsx
  client/src/components/atom/Title.tsx
  client/src/components/atom/select.tsx
  client/src/components/molecule/ProductCard.tsx
  client/src/components/molecule/ProductList.tsx
  client/src/components/molecule/ProductListTitle.tsx
  client/src/components/molecule/SearchBar.tsx
  client/src/components/organism/MainBox.tsx
  client/src/components/organism/topBar.tsx
  client/src/components/template/HomeTemplate.tsx
  client/src/utils/constants/constants.ts
  client/src/utils/types/eventFunction.ts
  client/src/utils/variables.scss
Labels: feature, migration, style

#25 refactor: 탑바, 사이드바와 메인 영역 템플릿화
  .github/ISSUE_TEMPLATE/✅-feature-template.md
  client/src/components/atom/MainBox.tsx
  client/src/components/atom/ProductImg.tsx
  client/src/components/organism/LeftNavBar.tsx
  client/src/components/organism/ProductListBox.tsx
  client/src/components/organism/TopBar.tsx
  client/src/components/template/HomeTemplate.tsx
Labels: refactor
